version: '3.8'

services:
  backend:
    container_name: chat-app-backend
    image: chat-app-backend
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${PORT}:${PORT}"

    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=production

    restart: always
